Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
    Enabled: false

AllCops:
  Exclude:
    - './Gemfile'
    - './spec/spec_helper.rb'

Metrics/BlockLength:
  Max: 180

Metrics/LineLength:
  Max: 180

Style/AsciiComments:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Metrics/AbcSize:
  Max: 25

