Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
    Enabled: false

AllCops:
  Exclude:
    - './Gemfile'
    - './spec/spec_helper.rb'

Metrics/BlockLength:
  Max: 110

Metrics/LineLength:
  Max: 110
